---

registry: ghcr.io/lioneljouin/meridio-experiment
tag: latest
pullPolicy: IfNotPresent

applicationName: a
replicas: 4

image: target-application
version: latest

networks: '[{"name":"macvlan-nad-1","interface":"net1","ips":["20.0.0.1/32"]},{"name":"macvlan-nad-2","interface":"net2","ips":["40.0.0.1/32"]}]'
